### ISSUE TITLE
Crack doesn't work :/

### ISSUE THREAD

**Issue by Shonenboi** [GameMakerStudio2Cracker/GameMakerStudio2Cracks#1]
![image](https://user-images.githubusercontent.com/65562868/82246008-40127a00-9944-11ea-8cc0-2295346fc2bc.png)

Hi,
I don't know why it say "REG_SZ" before c: ?

**Comment by GameMakerStudio2Cracker** [comment]
Please read the README.md.
It will probably contain answers for all your questions.
In this case there is a section called: "How do I crack without the Cracker.bat"?

Link: https://github.com/GameMakerStudio2Cracker/GameMakerStudio2Cracks#how-do-i-crack-without-the-crackerbateasier-with-the-crackerbat

**Comment by Shonenboi** [comment]
It doesn't work either :/ when i do this i have 0 functionality ^^, i think i will wait for another crack one day ! :D Thanks a lot for your work :)
