### ISSUE TITLE
Cant acces GMAcompiler

### ISSUE THREAD

**Issue by jkalter66** [GameMakerStudio2Cracker/GameMakerStudio2Cracks#3]

**Comment by GameMakerStudio2Cracker** [comment]
Do you mean this?
https://github.com/GameMakerStudio2Cracker/GameMakerStudio2Cracks#getting-access-to-the-path-xbingmassetcompilerexe-is-denied-error

**Comment by jkalter66** [comment]
It still wont work

**Comment by jkalter66** [comment]
![2Capture](https://user-images.githubusercontent.com/47828344/83166766-60c59700-a0dd-11ea-8b1c-a6aedb140edd.PNG)

**Comment by GameMakerStudio2Cracker** [comment]
The solutions in the README should solve it. Can you detail what you've tried?

**Comment by jkalter66** [comment]
I followed the instuctions im trying my special uninstaller program now

**Comment by jkalter66** [comment]
https://www.specialuninstaller.com/

**Comment by GameMakerStudio2Cracker** [comment]
Have you tried the 4th option?

**Comment by jkalter66** [comment]
wich regedit?

**Comment by GameMakerStudio2Cracker** [comment]
The 4th option is named `Download the runtime by yourself(#GameMaker won't let me download the Runtime!)`.

**Comment by jkalter66** [comment]
ok

**Comment by jkalter66** [comment]
I don see it

**Comment by GameMakerStudio2Cracker** [comment]
I honestly don't understand what's so troubling...
https://gyazo.com/dbb06be0729de3c14143f4a3d38e9e2f

**Comment by jkalter66** [comment]
ok

**Comment by jkalter66** [comment]
Thanks
